//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBlog.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UrlSlug { get; set; }
        public string ShortDecription { get; set; }
        public string Description { get; set; }
        public bool Published { get; set; }
        public System.DateTime PostOn { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PostTagMapId { get; set; }
    }
}
